### ISSUE TITLE
Select: Add ability to pass a color prop

### ISSUE THREAD

**Issue by bsbeeks** [mxenabled/mx-react-components#196]

**Comment by r-walsh** [comment]
@bsbeeks Which style specifically should the color prop effect? Currently effecting background-color [here](https://github.com/r-walsh/mx-react-components/blob/master/src/components/Select.js), though it would be easy to change.

**Comment by bsbeeks** [comment]
@r-walsh good catch. For some reason when I wrote this issue, I didn't see that option. User error =)

**Comment by r-walsh** [comment]
@bsbeeks No user error! I linked to my fork there so it isn't implemented for you guys yet. Just didn't want to submit a pull until I knew I was hitting the right CSS property.

**Comment by bsbeeks** [comment]
@r-walsh gotcha. So the passed in prop color should replace anywhere the default blue color is used. You can reference the demo/docs if needed. I believe the background color is the only place it's used.

**Comment by r-walsh** [comment]
@bsbeeks So I have the color prop functional, unfortunately I am also getting an eslint error that appears to be a problem in the mx-eslint-config. The error is preventing the build from running correctly.

I'm not super familiar with eslint, so if the problem is on my end I'd be happy to fix it.
```
ERROR in ./demo/app.js
Module build failed: Error: mx:
	Configuration for rule "react/display-name" is invalid:
	Value "data["0"].acceptTranspilerName" has additional properties.

Referenced from: /Users/ryanwalsh/projects/mx-react-components/.eslintrc
    at validateRuleOptions (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/config/config-validator.js:111:15)
    at /Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/config/config-validator.js:157:13
    at Array.forEach (native)
    at Object.validate (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/config/config-validator.js:156:35)
    at load (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/config/config-file.js:459:19)
    at /Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/config/config-file.js:355:36
    at Array.reduceRight (native)
    at applyExtends (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/config/config-file.js:338:28)
    at Object.load (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/config/config-file.js:464:22)
    at loadConfig (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/config.js:67:33)
    at getLocalConfig (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/config.js:129:23)
    at Config.getConfig (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/config.js:222:22)
    at processText (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/cli-engine.js:155:27)
    at CLIEngine.executeOnText (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint/lib/cli-engine.js:671:26)
    at lint (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint-loader/index.js:25:20)
    at Object.module.exports (/Users/ryanwalsh/projects/mx-react-components/node_modules/eslint-loader/index.js:111:3)
```

**Comment by bsbeeks** [comment]
The first thing to do is make sure your installed plugins match the versions listed here https://github.com/mxenabled/eslint-config-mx/blob/master/package.json#L23

**Comment by r-walsh** [comment]
#208 TravisCI pending. Thanks for being so responsive @bsbeeks
